### PR TITLE
Migrate to MPS 33

### PR DESCRIPTION
**Pull request by coolya**
I had to "fix" the project library of the project to make it work. See the commit messages for more details.

### CODE REVIEW

**Comment by mantkiew** [comment]
Thank you very much! Unfortunately, I cannot get MPS to find mbeddr modules. I configured

Global library
`com.mbeddr.core.base` to point to `c:/dev/mbeddr.core/code`

Path variables
`mbeddr.github.core.home` to point to `c:/dev/mbeddr.core`.

Is there anything else I have to set up? The instructions on [download page](http://mbeddr.com/download.html) mention 

> Create a library named mbeddr.core that points to the code directory of the github repository directory (/Users/peter/Documents/mbeddr.core/code).

Should I do `com.mbeddr.core` instead?  Note that the screenshot is also incorrect on that page.

**Comment by coolya** [comment]
I think you don't need that global library. The project has a project library pointing to the correct location using the `mbeddr.github.core.home` path variable. 

Since the global library is pointing to `/code` MPS might pick up old (unmigrated) models from `/code/applications`. Please try without that library and see if it works then.

I will also fix the website, later today.

**Comment by mantkiew** [comment]
Yes, that helped!

The only problem left is "Outdated model persistence is used. Please upgrade model persistence." in "_spreferences". I couldn't find anything in "Migrations" menu nor in Settings. How do we upgrade model persistence?

**Comment by coolya** [comment]
I think it should fix itself when the model is saved by MPS, which happens automatically. But to be sure I will put @slisson in the loop.

**Pull request closed without merging**
